/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainTicker;

import java.awt.Color;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Siddique
 */
public class TrainsTickers extends javax.swing.JFrame {

    String str;

    public TrainsTickers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        claSta = new javax.swing.JRadioButton();
        claEco = new javax.swing.JRadioButton();
        claFir = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ticSin = new javax.swing.JRadioButton();
        ticRe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cmbox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        route = new javax.swing.JLabel();
        cls = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Tno = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SubTotal = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 96)); // NOI18N
        jLabel1.setText("Train Ticketing System");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 96)); // NOI18N
        jLabel2.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        buttonGroup1.add(claSta);
        claSta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        claSta.setText("Standard");
        claSta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claStaActionPerformed(evt);
            }
        });

        buttonGroup1.add(claEco);
        claEco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        claEco.setText("Economy");

        buttonGroup1.add(claFir);
        claFir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        claFir.setText("First Class");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Ticket Type");

        buttonGroup2.add(ticSin);
        ticSin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ticSin.setText("Single");
        ticSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticSinActionPerformed(evt);
            }
        });

        buttonGroup2.add(ticRe);
        ticRe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ticRe.setText("Return");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Destination");

        cmbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rajshahi", "Chittagong", "Barisal", "Sylhet" }));
        cmbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmboxItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("To");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Dhaka");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("From");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claFir)
                    .addComponent(claSta)
                    .addComponent(jLabel3)
                    .addComponent(claEco))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticSin)
                    .addComponent(jLabel4)
                    .addComponent(ticRe))
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(cmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(ticSin)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticRe)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(claSta)
                        .addGap(18, 18, 18)
                        .addComponent(claEco)
                        .addGap(18, 18, 18)
                        .addComponent(claFir)
                        .addContainerGap())))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Class");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Ticket Type");

        route.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        route.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        cls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("From");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("To");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Date");

        to.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        from.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("Price");

        Type.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("Ticket No.");

        Tno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        dd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dd.setText("Time");

        time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("Route");

        price1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        price1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(dd))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cls, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dd)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        SubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Tax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("Total");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Sub Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(101, 101, 101)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(41, 41, 41)
                        .addComponent(jButton6)
                        .addGap(43, 43, 43)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claStaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claStaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claStaActionPerformed

    private void ticSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticSinActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SubTotal.setText(null);
        Tax.setText(null);
        Total.setText(null);
        cls.setText(null);
        from.setText(null);
        to.setText(null);
        date.setText(null);
        time.setText(null);
        Type.setText(null);

        Tno.setText(null);
        price1.setText(null);
        route.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        time.setText(tTime.format(timer.getTime()));

        SimpleDateFormat tdate = new SimpleDateFormat("dd-MMM-yyyy");
        date.setText(tdate.format(timer.getTime()));

        from.setText("Dhaka *");
        to.setText((String) cmbox.getSelectedItem() + " *");
        int num1;
        String ql = "";
        num1 = 1325 + (int) (Math.random() * 4238);
        ql += num1 + 1325;
        Tno.setText(ql);

        route.setText("ANY");
        cls.setText("STD");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        double tax = 15.50;
        double MilesK8 = 500.21;
        double MilesK12 = 600.54;
        double MilesK20 = 700.56;
        double MilesK30 = 800.11;
        double totalcost, eco = 200.00, fclass = 500.00;
        if (!(claSta.isSelected()) && !(claEco.isSelected()) && !(claFir.isSelected()) && !(ticSin.isSelected()) && !(ticRe.isSelected())) {
            SubTotal.setText(null);
            Tax.setText(null);
            Total.setText(null);
            cls.setText(null);
            from.setText(null);
            to.setText(null);
            date.setText(null);
            time.setText(null);
            Type.setText(null);
            Tno.setText(null);
            price1.setText(null);
            route.setText(null);
            JOptionPane.showMessageDialog(null, "Please select class & ticket type", "Use Class & Ticket Buttons", JOptionPane.INFORMATION_MESSAGE);
        } else if (!(ticSin.isSelected()) && !(ticRe.isSelected())) {
            SubTotal.setText(null);
            Tax.setText(null);
            Total.setText(null);
            cls.setText(null);
            from.setText(null);
            to.setText(null);
            date.setText(null);
            time.setText(null);
            Type.setText(null);
            Tno.setText(null);
            price1.setText(null);
            route.setText(null);
                        JOptionPane.showMessageDialog(null, "Please select ticket type", "Use Ticket type Buttons", JOptionPane.INFORMATION_MESSAGE);
        } else if (!(claSta.isSelected()) && !(claEco.isSelected()) && !(claFir.isSelected())) {
            Tax.setText(null);
            Total.setText(null);
            cls.setText(null);
            from.setText(null);
            to.setText(null);
            date.setText(null);
            time.setText(null);
            Type.setText(null);
            Tno.setText(null);
            price1.setText(null);
            route.setText(null);
            JOptionPane.showMessageDialog(null, "Please select ticket class", "Use Ticket Class Buttons", JOptionPane.INFORMATION_MESSAGE);
        } else if ((claSta.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = (tax * MilesK8) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", MilesK8 + totalcost);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("ONE WAY");

        } else if ((claSta.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = (tax * MilesK8) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK8 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("Return");
        } else if ((claEco.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = ((tax * MilesK8) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK8 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("One way");
        } else if ((claEco.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = ((tax * MilesK8) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK8 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("Return");
        } else if ((claFir.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = ((tax * MilesK8) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK8 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("One way");
        } else if ((claFir.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Barisal"))) {
            totalcost = ((tax * MilesK8) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK8);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK8 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("Return");
        } //Rajshahi
        else if ((claSta.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = (tax * MilesK12) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", MilesK12 + totalcost);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("ONE WAY");

        } else if ((claSta.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = (tax * MilesK12) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK12 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("Return");
        } else if ((claEco.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = ((tax * MilesK12) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK12 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("One way");
        } else if ((claEco.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = ((tax * MilesK12) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK12 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("Return");
        } else if ((claFir.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = ((tax * MilesK12) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK12 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("One way");
        } else if ((claFir.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Rajshahi"))) {
            totalcost = ((tax * MilesK12) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK12);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK12 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("Return");
        } //Sylhet
        else if ((claSta.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = (tax * MilesK20) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", MilesK20 + totalcost);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("ONE WAY");

        } else if ((claSta.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = (tax * MilesK20) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK20 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("Return");
        } else if ((claEco.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = ((tax * MilesK20) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK20 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("One way");
        } else if ((claEco.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = ((tax * MilesK20) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK20 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("Return");
        } else if ((claFir.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = ((tax * MilesK20) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK20 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("One way");
        } else if ((claFir.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Sylhet"))) {
            totalcost = ((tax * MilesK20) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK20);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK20 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("Return");
        } //Chittagong
        else if ((claSta.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = (tax * MilesK30) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", MilesK30 + totalcost);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("ONE WAY");

        } else if ((claSta.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = (tax * MilesK30) / 100;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK30 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("STD");
            Type.setText("Return");
        } else if ((claEco.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = ((tax * MilesK30) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK30 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("One way");
        } else if ((claEco.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = ((tax * MilesK30) / 100) + eco;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK30 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("ECO");
            Type.setText("Return");
        } else if ((claFir.isSelected()) && (ticSin.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = ((tax * MilesK30) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK30 + totalcost));
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("One way");
        } else if ((claFir.isSelected()) && (ticRe.isSelected()) && (cmbox.getSelectedItem().equals("Chittagong"))) {
            totalcost = ((tax * MilesK30) / 100) + fclass;
            String stax = String.format("tk%.2f", totalcost);
            Tax.setText(stax);
            String subT = String.format("tk%.2f", MilesK30);
            SubTotal.setText(subT);
            String T = String.format("tk%.2f", (MilesK30 + totalcost) * 2);
            Total.setText(T);
            price1.setText(T);
            cls.setText("F.Class");
            Type.setText("Return");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void cmboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboxItemStateChanged
        str = (String) cmbox.getSelectedItem();
    }//GEN-LAST:event_cmboxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainsTickers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel Tno;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Type;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton claEco;
    private javax.swing.JRadioButton claFir;
    private javax.swing.JRadioButton claSta;
    private javax.swing.JLabel cls;
    private javax.swing.JComboBox<String> cmbox;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel from;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel route;
    private javax.swing.JRadioButton ticRe;
    private javax.swing.JRadioButton ticSin;
    private javax.swing.JLabel time;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
